export interface Product {
  "id": number,
  "title": string,
  "productVariationTitle": string,
  "score": number,
  "barcode": string,
  "rating": number,
  "type": string,
  "discount": number,
  "description": string,
  "price": number,
  "productTitle": string,
  "productId": string | number | null,
  "brandId": string,
  "brandTitle": string,
  "brandLogo": string,
  "brandDescription": string | number | null,
  "vat": number,
  "disabledUntil": boolean,
  "containerPrice": number,
  "featured": string,
  "images": {
    "imageThumbnailSrc": string,
    "imageSrc": string,
    "imageUserType": string,
    "isDefault": boolean,
  }[],
  "highlight": string,
  "popularityBadgeName": string,
  "popularityBadgeURL": string,
  "productToppings": any[],
  "capacity": number,
  "active": boolean,
  "discountRatio": number,
  "vendorLogo": string,
}
